name: Index Generation

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Generate Index
        run: |
          python code/generate_index.py
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Generate Index
          author: GitHub Action <action@github.com>
          committer: GitHub Action <action@github.com>
          signoff: true
          branch: index-generator
          title: "[AUTO] Update Index"
          body: |
            Update Index
