name: Index Generation

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Generate Index
        run: |
          python code/generate_index.py

      - uses: EndBug/add-and-commit@v6
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: "Update index"
          signoff: true
